### ISSUE TITLE
Historian headers and meta needs to be written and read from the historians.

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#311]
Headers should be preserved through the base historian.

- [ ] metadata should be added to the the historian and be returned during query.
 - [x] SQL Historian (sqlite version)
 - [x] SQL Historian (mysql version)
 - [ ] MongoDB Historian
- [ ] headers need to be added for points.
 - [ ] SQL Historian (sqlite version)
 - [ ] SQL Historian (mysql version)
 - [ ] MongoDB Historian
