### ISSUE TITLE
VC TODO

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#481]
- [x] Add lookup of identity through agent uuid.  This is done through a core service call.
- [x] Persist the registered platforms.
- [x] There are duplicates in the platforms registry if agent is reinstalled.
- [x] There should be bi-directional connection tasks if platform or vc disconnects.
- [x] VC Platform should have a method to set the platform_uuid on it.  That uuid will be used when reporting platform statistics.
- [x] VC Platform needs to use the platform_uuid to report it's status.
- [x] Tree is built dynamically based on the available topics (available in historian)
- [x] Auto register "local to vc" platform agent.
- [x] When platform is started after volttron-cfg is run it should autoregister with volttron central.

- [ ] Install agent.
- **volttron-cfg fixes**
 - [x] Installs volttron central
 - [x] Installs volttron central platform
 - [x] Installs platform historian.
 - [x] Uses specified VOLTTRON_HOME in environment.
 - [x] Auto register installed volttron central platform (during next startup is fine).
 - [x] Use a default external IP address (localhost) in volttron-cfg. Otherwise it uses an empty string and the resulting configuration files are invalid.
- **VC Interface**
 - [x] Auto registered platform does not show up initially. It requires a manual reload of the page.
 - [x] Transition to a specific platform from the platforms page fails.
 - [x] No notification of login failure.
 - [x] Tree isn't populated when loging in.
 - [x] When logging in dashboard should always be the first page.
 - [x] Add device data under platform.  Platforms now report devices from 2 different rpc calls.  From top level list_devices or from platfrom get_devices.  See new_register.html for calls.
 - [x] Route to Charts when check box for a point.
 - [x] For tooltip statuses, translate GOOD to Healthy, BAD to Unhealthy, etc.
 - [ ] Fix timing issue that prevents performance stats from not loading in tree initially.
- **Masterweb issues**
 - [x] Logging is happening even though process is in the background ... investigate pywsgi issue here.

**Comment by jchap-pnnl** [comment]
To dynamically add devices to the tree, the data returned by the devices query will be fit into the following structure:

"platforms":` {
- "4687fedc-65ba-43fe-21dc-098765bafedc": {
  - "uuid": "4687fedc-65ba-43fe-21dc-098765bafedc",
  - "name": "CAMPUS1",
  - "status": "GOOD",
  - "children": ["buildings"],
  - "path": ["platforms", "4687fedc-65ba-43fe-21dc-098765bafedc"],
  - "buildings": {             
      - "path": ["platforms", "4687fedc-65ba-43fe-21dc-098765bafedc", "buildings"],
      - "name": "Buildings",
      - "status": "GOOD",
      - "children": ["1111fedc-65ba-43fe-21dc-098765bafede"],
      - "1111fedc-65ba-43fe-21dc-098765bafede": {
        - "uuid": "1111fedc-65ba-43fe-21dc-098765bafede",
        - "name": "BLG1",
        - "status": "GOOD",
        - "children": ["devices"],
        - "path": ["platforms", "4687fedc-65ba-43fe-21dc-098765bafedc", "buildings", "1111fedc-65ba-43fe-21dc-098765bafede"],
        - "devices": {       
          - "path": ["platforms", "4687fedc-65ba-43fe-21dc-098765bafedc", "buildings", "1111fedc-65ba-43fe-21dc-098765bafede", "devices"],
          - "name": "Devices",
          - "status": "GOOD",
          - "children": ["1231fedc-65ba-43fe-21dc-098765bafedl"],
          - "1231fedc-65ba-43fe-21dc-098765bafedl": {
            - "uuid": "1231fedc-65ba-43fe-21dc-098765bafedl",
            - "name": "RTU1",
            - "status": "GOOD",
            - "path": ["platforms", "4687fedc-65ba-43fe-21dc-098765bafedc", "buildings", "1111fedc-65ba-43fe-21dc-098765bafede", "devices", "1231fedc-65ba-43fe-21dc-098765bafedl"],

**Comment by jchap-pnnl** [comment]
Can we change the object returned by the get_devices method to:

result: {
  - path: "PNNL/2400_STEVENS/HEATER1",
  - health: {
    - "status": "GOOD",
    - "last_updated": "2016-05-02T22:28:34.079391+00:00",
    - "context": null }
  - "last_published_utc": "2016-05-02T22:28:31.851270+00:00",
  - "points": [ "HPWH_Phy0_PowerState", "Heartbeat", "temperature", "ERWH_Phy0_ValveState"] } }

That way the front end can get the path by result.path rather than have to do a loop to get the lone key attribute? Also health.status would be consistent with list_platforms and list_agents.

**Comment by jchap-pnnl** [comment]
I deleted the previous comment, realizing it wouldn't be a loop for a single key attribute. Rather, there will be N keys for N device objects. That works then. But health.status would still be better.
